# Generated by Django 4.0.2 on 2022-02-14 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myres', '0006_alter_myres_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myres',
            name='user',
            field=models.OneToOneField(default='User.id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
