# Generated by Django 4.0.2 on 2022-02-14 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myres', '0009_alter_myres_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Myres',
        ),
    ]
