# Generated by Django 4.0.2 on 2022-02-14 09:56

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('myres', '0011_myres'),
    ]

    operations = [
        migrations.AddField(
            model_name='myres',
            name='mobile_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True),
        ),
    ]
