# Generated by Django 4.0.2 on 2022-02-14 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myres', '0012_myres_mobile_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Myres',
        ),
    ]
