# Generated by Django 4.0.2 on 2022-02-14 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myres', '0014_myres'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtendedUser',
        ),
    ]
