# Generated by Django 4.0.2 on 2022-02-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myres', '0015_delete_extendeduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myres',
            name='about_me',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='myres',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='myres',
            name='hobby',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='myres',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='myres',
            name='skills',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='myres',
            name='working_experience',
            field=models.TextField(blank=True),
        ),
    ]
