# Generated by Django 4.0.2 on 2022-02-14 12:12

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('myres', '0020_myres_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myres',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='myres',
            name='education',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='myres',
            name='mobile_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True),
        ),
    ]
