# Generated by Django 4.0.2 on 2022-02-15 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myres', '0021_alter_myres_birthday_alter_myres_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myres',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
