# Generated by Django 4.0.2 on 2022-02-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myres', '0023_certificates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificates',
            name='photo',
            field=models.ImageField(upload_to='certificates/%Y/%m/%d/'),
        ),
    ]
