# Generated by Django 4.0.2 on 2022-02-16 10:47

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('myres', '0024_alter_certificates_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myres',
            name='mobile_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
