# Generated by Django 4.0.2 on 2022-02-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myres', '0025_alter_myres_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='myres',
            name='name',
            field=models.TextField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='myres',
            name='surname',
            field=models.TextField(max_length=254, null=True),
        ),
    ]
