# Generated by Django 4.0.2 on 2022-02-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myres', '0026_myres_name_myres_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='myres',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время создания'),
        ),
    ]
